name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Known Hosts
        run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with Rsync
        run: |
          rsync -avz --delete ./ ${{ secrets.USER }}@${{ secrets.DROPLET_IP }}:/home/${{ secrets.USER }}/morning-motivation

      - name: Restart Application Using Docker Compose
        run: |
            ssh -o StrictHostKeyChecking=no -T ${{ secrets.USER }}@${{ secrets.DROPLET_IP }} "
              cd /home/${{ secrets.USER }}/morning-motivation && \
              docker-compose down && \
              docker-compose up -d --build
            "